import Landing from "@/components/sections/landing/Landing";
import Head from "next/head";
import { GetServerSideProps } from "next";
import { Suspense, lazy } from "react";

export default function Home() {
  // Lazy load the components
  const Properties = lazy(
    () => import("@/components/sections/properties/Properties")
  );
  const TeamMembers = lazy(
    () => import("@/components/sections/team-members/TeamMembers")
  );
  const About = lazy(() => import("@/components/sections/about/About"));
  const Contact = lazy(() => import("@/components/sections/contact/Contact"));
  const Invest = lazy(() => import("@/components/sections/invest/Invest"));

  return (
    <>
      <Head>
        <title>Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <Landing />
        <Suspense fallback={<div>Loading...</div>}>
          <About />
        </Suspense>
        <Suspense fallback={<div>Loading...</div>}>
          <TeamMembers />
        </Suspense>
        <Suspense fallback={<div>Loading...</div>}>
          <Properties />
        </Suspense>
        <Suspense fallback={<div>Loading...</div>}>
          <Invest />
        </Suspense>
        <Suspense fallback={<div>Loading...</div>}>
          <Contact />
        </Suspense>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};
