import About from "@/components/sections/about/About";
import Contact from "@/components/sections/contact/Contact";
import Invest from "@/components/sections/invest/Invest";
import Landing from "@/components/sections/landing/Landing";
import Properties from "@/components/sections/properties/Properties";
import TeamMembers from "@/components/sections/team-members/TeamMembers";
import Head from "next/head";
import { GetServerSideProps } from "next";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <Landing />
        <About />
        <TeamMembers />
        <Properties />
        <Invest />
        <Contact />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  };
};
